### ISSUE TITLE
crash when tapping youtube thumbnails

### ISSUE THREAD

**Issue by sleeksorrow** [klinker24/Talon-for-Twitter#16]
Hi! When I tap on youtube thumbnails, Talon just crashes.

If this is because I did not put in a youtube api key, then I would suggest to fallback to giving the youtube url to the system to open it in browser/youtube app instead of crashing. ;)

If that's not the reason, then I'd like to ask for help here.

Thank you!

**Comment by klinker24** [comment]
Please post the log or else I do not know what is making it crash

**Comment by klinker24** [comment]
Since I have not gotten any other reports of this, I am closing it
