### ISSUE TITLE
Library not found: org.apache.http.legacy

### ISSUE THREAD

**Issue by mcbyte-it** [klinker24/Talon-for-Twitter#20]
I am trying to rebuild Talon for my personal use, but it is not working, I am getting this error:

> Error: A problem occurred configuring root project 'Talon-for-Twitter'.
> \> Unable to find optional library: org.apache.http.legacy

**Comment by klinker24** [comment]
Are you using the latest build tools and android sdk 23?

This line in the gradle file has to be added to work on marshmallow. If you are targeting a different version of android with your build, then it can be removed, but be sure to grab the correct version of the android support libraries.

**Comment by mcbyte-it** [comment]
I am building the project as it is, with same sdk and target, I have latest SDK downloaded and updated. I am running latest stable Android Studio 1.5.1.

I also tried downloading a fresh copy from github and opening it with Android studio, and running a build, same error message.

**Comment by mcbyte-it** [comment]
Now it builds successfully, found the solution here: http://stackoverflow.com/a/33970130/2024535

**Comment by klinker24** [comment]
Wild, but great, enjoy the app
