### ISSUE TITLE
Build fails: could not find com.lapism:searchview:2.2

### ISSUE THREAD

**Issue by karlicoss** [klinker24/Talon-for-Twitter#27]
Hey, I'm getting this error while trying to build Talon. I guess, version 2.2 of this artifact was removed from [bintray](https://bintray.com/lapism/maven/searchview/2.2/view) (google index still remembers the page).

P.S. actually, I'm surprised you don't have Travis CI, if you are interested I could make a PR and integrate Talon with it, then we could detect failures like this one earlier :)

```
./gradlew assembleDebug
Incremental java compilation is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'Talon-for-Twitter'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find com.lapism:searchview:2.2.
     Searched in the following locations:
         https://repo1.maven.org/maven2/com/lapism/searchview/2.2/searchview-2.2.pom
         https://repo1.maven.org/maven2/com/lapism/searchview/2.2/searchview-2.2.jar
         https://jcenter.bintray.com/com/lapism/searchview/2.2/searchview-2.2.pom
         https://jcenter.bintray.com/com/lapism/searchview/2.2/searchview-2.2.jar
         https://oss.sonatype.org/content/repositories/snapshots/com/lapism/searchview/2.2/searchview-2.2.pom
         https://oss.sonatype.org/content/repositories/snapshots/com/lapism/searchview/2.2/searchview-2.2.jar
         file:/L/repos/other/Talon-for-Twitter/lib/searchview-2.2.jar
         file:/L/repos/other/Talon-for-Twitter/lib/searchview.jar
         file:/L/soft/android-sdk-linux/sdk/extras/android/m2repository/com/lapism/searchview/2.2/searchview-2.2.pom
         file:/L/soft/android-sdk-linux/sdk/extras/android/m2repository/com/lapism/searchview/2.2/searchview-2.2.jar
         file:/L/soft/android-sdk-linux/sdk/extras/google/m2repository/com/lapism/searchview/2.2/searchview-2.2.pom
         file:/L/soft/android-sdk-linux/sdk/extras/google/m2repository/com/lapism/searchview/2.2/searchview-2.2.jar
     Required by:
         :Talon-for-Twitter:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.519 secs

```

**Comment by klinker24** [comment]
I actually use Jenkins, but... I only build the material design version of talon on it. Guess there is merit in turning it back on for this project as well. Thanks.

Strange enough, building works just fine for me, I am able to find that library and include it in the build with that 2.2 version number. I will look into updating it, but there were some things that broke when updated.

**Comment by karlicoss** [comment]
@klinker24 tried again, still no luck. As far as I understand the artifact should be [here](https://bintray.com/lapism/maven/searchview/view), but I only see versions 3.x there.

Btw, I guess it might work for you since it is cached in your local gradle cache.

**Comment by vwillcox** [comment]
If you could help with fix this, I would happily donate to a good cause :+1: I would love to get this to compile so I can have a personalised Twitter client

**Comment by behelit** [comment]
Why was this closed? It still appears to be a problem.

> Could not find com.lapism:searchview:2.2
