### ISSUE TITLE
Unable to obtain article key

### ISSUE THREAD

**Issue by sleeksorrow** [klinker24/Talon-for-Twitter#33]
The explanation for the acticle key is:
"This Article key is to use the readability browser. To get yours, visit https://article.klinker.xyz"

This URL is not accessable (connection refused). Since it ends on "klinker.xyz" I assume that's driven by you and so I thought I might raise that here. Thanks!

**Comment by klinker24** [comment]
Sorry, I will update that link: https://article.klinkerapps.com/developer
