### ISSUE TITLE
Slow refresh of newsfeed when unfollowing someone

### ISSUE THREAD

**Issue by waltsims** [klinker24/Talon-for-Twitter#35]
After unfollowing someone, newsfeed does not refresh without that person's tweets.  Refreshing the feed, and closing the app doesn't seem to help.  After 1.5 hours, repeating the app initialisation steps seemed to work.

**Comment by klinker24** [comment]
The app doesn't remove tweets from people you have unfollowed. It just won't show any in the future. This is working the way I have it designed. If you really don't want to see their tweets, you could mute that user after unfollowing
