### ISSUE TITLE
Support for DM group conversations

### ISSUE THREAD

**Issue by sleeksorrow** [klinker24/Talon-for-Twitter#36]
Hi there, thanks for your stunning client.

I'd like to ask if there is a possibility to add support for DM group conversations. 1-to-1 DMs work normally, but as soon as I am part of a DM group, I don't see the whole conversation, like as if it doesn't exist.

**Comment by klinker24** [comment]
No this isn't possible, unfortunately. Twitter doesn't allow third party apps to access group dms.

https://dev.twitter.com/rest/reference/get/direct_messages
